export type Case = {
  slug: string;
  titel: string;
  undertitel: string[];
  date: string;
  billede: string;
  gif: string;
  text: string[];
  imgdisplay: string[];
};

export const casearray: Case[] = [
  {
    slug: "pixeline",
    titel: "AI Mascot Generator: Pixeline",
    undertitel: [
      "Training Flux LoRA to recreate Pixeline in images",
    ],
    date: "2025-11-05",
    billede: "/cases/pixeline/pixeline.png",
    gif: "/cases/pixeline/pixeline.gif",
    text: [
      "This project has been developed as part of coursework and is solely for non-commercial use. All rights belong to the original rights holders.",
      `“[Brand] needs a new campaign website. It is important to [Brand] that [Mascot] is included in all marketing materials. The deadline is approaching, so their marketing department cannot manage to build the website, or to include [Mascot].`,
      `By using AI, we can automate and streamline the production of content, thereby opening up a more agile and free process."”`,
      "Pixeline, text, icons and background images are generated by artificial intelligence.",
    ],
    imgdisplay: [
      "/cases/pixeline/pixeline01.png",
      "/cases/pixeline/pixeline02.png",
      "/cases/pixeline/pixeline03.png",
      "/cases/pixeline/pixeline04.png",
      "/cases/pixeline/pixeline05.png",
      "/cases/pixeline/pixeline06.png",
      "/cases/pixeline/pixeline07.png",
      "/cases/pixeline/pixeline08.png",
      "/cases/pixeline/pixeline09.png",
    ],
  },
  {
    slug: "handicaploftet",
    titel: "Data visualization of Handicapløftet",
    undertitel: [
    ],
    date: "2025-12-05",
    billede: "/cases/handicaploftet/danmarkskort.png",
    gif: "/cases/handicaploftet/handi.gif",
    text: [
        "Data visualization of selected signatories in municipalities and regions in connection with the 2025 local elections.",
        "Handicapløftet:",
        `"As an elected representative, I will fight for:`,
        "Strengthening rights and legal protection in case processing - also for those who never apply or complain",
        "Ensuring high professional standards - in residential facilities, schools, and all other initiatives",
        "Ensuring accompaniment for all people in need - this is a prerequisite for wellbeing and participation",
        "Strengthening health and wellbeing - specifically ensuring the implementation of health checks for people in the municipality's residential facilities",
        "Strengthening quality and ambitions for all students with developmental disabilities in primary school - in mainstream education, in special classes and at special schools",
        `Ensuring protection and supervision of conditions for people in social services"`
    ],
    imgdisplay: [
        "/cases/handicaploftet/handi_01.png",
        "/cases/handicaploftet/handi_02.png",
    ],
  },
  {
    slug: "munich",
    titel: "City Branding: Munich",
    undertitel: [
      "Dynamic visual identity",
    ],
    date: "2026-02-06",
    billede: "/cases/munich/pattern.png",
    gif: "/cases/munich/munich.gif",
    text: [
      "I have designed a visual identity for Munich based on the city's flag, which consists of black and yellow diamonds.",
      "The diamond is split into triangles, which serve as the identity's modular building blocks. The triangles can be combined freely and create a dynamic, changeable system."
    ],
    imgdisplay: [
        "/cases/munich/munich01.png",
        "/cases/munich/munich02.png",
        "/cases/munich/munich03.png",
        "/cases/munich/munich04.png",
        "/cases/munich/munich05.png",
        "/cases/munich/munich06.png",
        "/cases/munich/munich07.png",
    ],
  },
  {
    slug: "pi-day",
    titel: "Poster generator for Pi Day",
    undertitel: [
      "Interactive poster"
    ],
    date: "2024-11-29",
    billede: "/cases/piday/piday01.png",
    gif: "/cases/piday/piday.png",
    text: [
      `The motif on the poster is inspired by pi. Selected variables in the sketch can be controlled with the mouse and keyboard, and the poster can be exported as a png by pressing 'v'.`,
      "The sketch is made in Processing."
    ],
    imgdisplay: [
        "/cases/piday/piday_right.gif",
        "/cases/piday/piday_rotate.gif",
        "/cases/piday/piday_zoom.gif",

    ],
  },
  {
    slug: "sakura island",
    titel: "Blender: Sakura island",
    undertitel: [
    ],
    date: "2024-11-15",
    billede: "/cases/sakura/sakura.png",
    gif: "/cases/sakura/sakura.gif",
    text: [
      "Visualization of my own island in a 3D environment based on shape, color and composition."
    ],
    imgdisplay: [
      "/cases/sakura/sakura1.gif",
      "/cases/sakura/sakura2.gif",
      "/cases/sakura/sakura3.gif",
    ],
  },
  {
    slug: "shecanplay",
    titel: "Rebrand of SheCanPlay",
    undertitel: [
      "Koncept: formlessness"
    ],
    date: "2025-12-12",
    billede: "/cases/shecanplay/shecanplay8.png",
    gif: "/cases/shecanplay/shecanblob.gif",
    text: [
      `“You can remain formless. You can take a form. You can take a form now, you can take a form later. Your choice, your need.”`,
      "SheCanPlay is a Danish nonprofit organization that works to strengthen young women's and gender minorities' participation, visibility and opportunities in the music industry. The organization offers free talent development programs, community, industry insight and access to creative facilities.",
      `The organization desires a visual identity that opens up for an 'endorsed brands' structure for the artists who wish to signal their affiliation with SheCanPlay, without overpowering the emerging artist's own identity.`
    ],
    imgdisplay: [
      "/cases/shecanplay/shecanplay1.png",
      "/cases/shecanplay/shecanplay2.png",
      "/cases/shecanplay/shecanplay3.png",
      "/cases/shecanplay/shecanplay4.png",
      "/cases/shecanplay/shecanplay5.png",
      "/cases/shecanplay/shecanplay6.png",
      "/cases/shecanplay/shecanplay7.png",
      "/cases/shecanplay/shecanplay8.png",
      "/cases/shecanplay/shecanplay9.png",
      "/cases/shecanplay/shecanplay10.png",
      "/cases/shecanplay/shecanplay11.png",
    ],
  },
  {
    slug: "aaben",
    titel: "Label generator for Åben øl",
    undertitel: [
    ],
    date: "2026-03-06",
    billede: "/cases/aaben/aaben00.png",
    gif: "/cases/aaben/aaben.gif",
    text: [
      "Conceptualization, design and coded solution of a visual design system, which ÅBEN can use to create label designs for their many different beers.",
      "Coded with p5.js and three.js."
    ],
    imgdisplay: [
      "/cases/aaben/aaben08.png",
      "/cases/aaben/aaben07.png",
      "/cases/aaben/aaben06.png",
      "/cases/aaben/aaben02.png",
      "/cases/aaben/aaben03.png",
      "/cases/aaben/aaben05.png",
      "/cases/aaben/aaben01.png",
      "/cases/aaben/aaben09.jpg",
      "/cases/aaben/aaben04.jpg",
      
    ],
  },
  {
    slug: "plotter",
    titel: "Plotter art generator",
    undertitel: [
    ],
    date: "2024-12-20",
    billede: "/cases/prikker/plotte-prikker.png",
    gif: "/cases/prikker/prikker.gif",
    text: [
      "Browser-based sketch in p5.js, which can export SVG files that can be plotted on an AxiDraw machine.",
      "The interface can control selected variables in the sketch via Shoelace."
    ],
    imgdisplay: [
      "/cases/prikker/plotte-prikker.png",
      "/cases/prikker/prikker2.png",
      "/cases/prikker/prikker3.png",
    ],
  },
  {
    slug: "monsterbird",
    titel: "Monster bird",
    undertitel: [
    ],
    date: "2024-12-16",
    billede: "/cases/monster/monster3.png",
    gif: "/cases/monster/monster.gif",
    text: [
      "My own version of the game Flappy Bird in a universe of neon, monsters and acid.",
      "This project has been developed as part of coursework and is solely for non-commercial use. All rights belong to the original rights holders.",
    ],
    imgdisplay: [
      "/cases/monster/monster1.png",
      "/cases/monster/monster2.png",
      "/cases/monster/monster3.png",
    ],
  },
];
